//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsData {
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    public partial class GarmentsEntities : DbContext {
        public GarmentsEntities()
            : base("name=GarmentsEntities") {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder) {
            //throw new UnintentionalCodeFirstException();
            MapCategory(modelBuilder);
            //modelBuilder.Entity<Category>().Ignore(x => x.CategoryId);
        }

        public DbSet<Category> Categories { get; set; }
        public DbSet<Product> Products { get; set; }
        private void MapCategory(DbModelBuilder modelBuilder) {
            //modelBuilder.Entity<Category>().Ignore(x => x.CategoryId);
            //modelBuilder.Entity<Category>().HasKey(x => x.CategoryId).Property(x => x.CategoryId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

            modelBuilder.Entity<Category>()
                .HasKey(x => x.CategoryId);

            modelBuilder.Entity<Category>()
                .Property(x => x.CategoryId)
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

            modelBuilder.Entity<Category>().Property(x => x.Name)
                .IsRequired()
                .HasMaxLength(255);

            modelBuilder.Entity<Category>().HasOptional(x => x.Parent)
                .WithMany(x => x.Children)
                .HasForeignKey(x => x.ParentCatId)
                .WillCascadeOnDelete(false);

        }
    }


}
