//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarmentsEntities {
    using System;

    public partial class Product {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Price { get; set; }

        public virtual Category Category { get; set; }
    }
}
